#! /bin/bash
if [ -d ~/Study/github/hosts ] ; then
cd ~/Study/github/hosts/
git pull 
else
mkdir  -p ~/Study/github/
cd ~/Study/github/
git clone https://github.com/racaljk/hosts
cd ~/Study/github/hosts/
fi
sudo cp hosts /etc/
